Hw03 mongodb done
albatrozzz/nodejs-homework-rest-api pull request #2
Opened 2022-01-29 18:40 UTC by albatrozzz

2022-01-30 07:41 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const contact = await Contact.findById(req.params.contactId)
сделать дополнительную проверку на валидность ид
mongoose.Types.ObjectId.isValid

2022-01-30 07:42 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if(error.message.includes("Cast to ObjectId failed")){
удалить

2022-01-30 07:46 UTC, KirillKulakow requested changes
need fix

2022-01-30 07:46 UTC, KirillKulakow commented on routes/api/contacts.js
>      if (!req.body.name || !req.body.email || !req.body.phone){
так у тебя есть схема для валидации - поставь там везде required и удали данную проверку

2022-01-30 07:46 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const response = await Contact.findByIdAndDelete(req.params.contactId)
проверка ид

2022-01-30 07:46 UTC, KirillKulakow commented on routes/api/contacts.js
>      if (!req.body.name && !req.body.email && !req.body.phone){
сюда можно сделать отдельную схему

2022-01-30 07:46 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const updatedContact = await Contact.findByIdAndUpdate(req.params.contactId, req.body, {new: true})
проверка ид

2022-01-30 07:46 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const result = await Contact.findByIdAndUpdate(req.params.contactId, req.body, {new: true})
проверка ид

2022-01-31 20:36 UTC, KirillKulakow commented on middlewares/contacts/idValidation.js
> +    console.log(id)
удалить лог

2022-01-31 20:42 UTC, KirillKulakow commented on routes/api/contacts.js
> +const {Contact, schemas} = require('../../models/contacts.js')
окончание .js можно не писать

2022-01-31 20:45 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if(error.message.includes("validation failed")){
удалить этот иф - потому что не несет никакого смысла
что с ним, что без него результат будет одинаковый

2022-01-31 20:46 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if(!req.body.favorite){
если у тебя favorite будет false будет ошибка

2022-01-31 20:46 UTC, KirillKulakow requested changes
need fix

2022-02-01 20:32 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if(error.message.includes("is required")){
зачем тебе эта проверка? этот message возвращает mongoose при валидации, но ответ тебе не прийдет, потому что у тебя для валидации есть JOI
Тоесть у тебя есть проверка `const {error} = schemas.add.validate(req.body);` и здесь ты еще раз проверку делаешь - зачем?

2022-02-01 20:33 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("is required")){
тот же вопрос

2022-02-01 20:33 UTC, KirillKulakow approved these changes

2022-02-02 05:36 UTC, albatrozzz commented on routes/api/contacts.js
> +    if(error.message.includes("is required")){
Просто потому, что в ДЗ прописано, какой ответ должен возвращаться в случае ошибки. До валидации mongoose дело не доходит, потому что JOI в дело вступает и возвращает не то сообщение, которое надо. Так что либо отказываться от JOI в данном случае и надеяться только на валидацию mongoose, либо вот эту проверку писать.

2022-02-02 05:36 UTC, albatrozzz commented on routes/api/contacts.js
> +    if (error.message.includes("is required")){
Просто потому, что в ДЗ прописано, какой ответ должен возвращаться в случае ошибки. До валидации mongoose дело не доходит, потому что JOI в дело вступает и возвращает не то сообщение, которое надо. Так что либо отказываться от JOI в данном случае и надеяться только на валидацию mongoose, либо вот эту проверку писать.

2022-02-02 05:37 UTC, merged

2022-02-02 18:33 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if(error.message.includes("is required")){
Попробуй удалить эту проверку и увидишь что ничего не поменяется
Так как ты юзаешь createError в котором ты уже проставляешь статус 400